### ISSUE TITLE
Customers are not generated

### ISSUE THREAD

**Issue by HalBenHB** [DurthVadr/TBD---Tropical-Beach-Diner#22]
JSON Response: {"results":[{"name":{"title":"Miss","first":"Rebecca","last":"Bates"}}],"info":{"seed":"f0e3a6c5303ef8b5","results":1,"page":1,"version":"1.4"}}
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.ObjectMapper
	at GameEngine.CustomerManager.fetchRandomName(CustomerManager.java:49)
	at GameEngine.CustomerManager.createCustomer(CustomerManager.java:25)
	at GameEngine.GameLogic$1.lambda$run$0(GameLogic.java:79)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonView [in thread "AWT-EventQueue-0"]
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:37)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
	... 16 more

**Comment by DurthVadr** [comment]
Issue is about Maven pom.xml and possibly with the package names. did mvn clean install fix? because API side and code is looking correct

**Comment by DurthVadr** [comment]
![Uploading DpQ9YJl.jpg…]()
